input()
print('hola bro')
input()
print('un g de que?')
input()
print('sisi')
print('350 y 500 unas indoor')
input()
print('dalee')
input()
print('voy a estar x la plaza d los bomberos tipo 6')
input()
print('joya broderrr')

